services:
  - name: knote-database
    type: psql
    psqlVersion: 17
    plan: free

  - name: knote
    type: web
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: knote-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: true